version: '3.8'
services:
  backend:
    build:
      context: ..\bookstore-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080

  frontend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      - API_BASE=http://backend:8080/api
    depends_on:
      - backend